apiVersion: v1
kind: Pod
metadata:
  name: nginx-extra
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx:alpine
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    value: null
    effect: "NoSchedule"

