apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-demo2
spec:
  containers:
  - name: quota-mem-cpu-demo-ctr2
    image: nginx
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m" 
      requests:
        memory: "600Mi"
        cpu: "400m"
